#!/bin/sh

case "$(playerctl -l)" in
  spotify|google-play-music-desktop-player)
    playerctl next
    ;;
esac

if [ -n "$(pidof pianobar)" ]; then
  echo -n 'n' > ~/.config/pianobar/ctl
  exit
fi

if [ -n "$(pidof mplayer)" ]; then
  echo 'pt_step 1' > /tmp/mplayer
  exit
fi
