#!/bin/sh

# player=$(playerctl -l | grep -v chromium)
# player=$(playerctl -l)

# echo $player

# case "$player" in
#   spotify|spotifyd|ncspot|clementine|chrom*)
#     playerctl -p $player next
#     exit
#     ;;
#   tizonia*)
#     tizonia-remote next
#     exit
#     ;;
# esac

if [ -n "$(pidof pianobar)" ]; then
  echo -n 'n' > ~/.config/pianobar/ctl
  exit
fi

if [ -n "$(pidof mplayer)" ]; then
  echo 'pt_step 1' > /tmp/mplayer
  exit
fi

if [ -n "$(pidof cmus)" ]; then
  cmus-remote -n
  exit
fi

playerctl next
