#!/bin/sh

player=$(playerctl -l)
#player=$(playerctl -l|grep -v chrom)
#playing=$(pacmd list-sink-inputs|grep -A 20 RUNNING|grep application.name|cut -d\" -f2|tr 'A-Z' 'a-z')

if [ -n "$(pidof pianobar)" ]; then
  echo -n 'p' > ~/.config/pianobar/ctl
  exit
fi

if [ -n "$(pidof mplayer)" ]; then
  echo 'pause' > /tmp/mplayer
  exit
fi

if [ -n "$(pidof cmus)" ]; then
  cmus-remote -u
  exit
fi

if [ -n "$(pidof sconsify)" ]; then
  sconsify -command play_pause
  exit
fi

#echo $player | grep -q $playing
#if [ $? -eq 0 ]; then
#    playerctl -p $playing play-pause
#fi

case "$player" in
  spotify|spotifyd|ncspot|clementine|chrom*)
    playerctl -p $player play-pause
    exit
    ;;
esac
