#!/bin/sh

# player=$(playerctl -l|grep -v chromium)
# player=$(playerctl -l)
# playing=$(pacmd list-sink-inputs|grep -A 20 RUNNING|grep application.name|cut -d\" -f2|tr 'A-Z' 'a-z')

# case "$player" in
#   spotify|spotifyd|ncspot|clementine|chrom*)
#     playerctl -p $player play-pause
#     exit
#     ;;
#   tizonia*)
#     tizonia-remote pause
#     exit
#     ;;
# esac


if [ -n "$(pidof pianobar)" ]; then
  echo -n 'p' > ~/.config/pianobar/ctl
  exit
fi

if [ -n "$(pidof mplayer)" ]; then
  echo 'pause' > /tmp/mplayer
  exit
fi

if [ -n "$(pidof cmus)" ]; then
  cmus-remote -u
  exit
fi

if [ -n "$(pidof sconsify)" ]; then
  sconsify -command play_pause
  exit
fi

playerctl play-pause
