#!/bin/sh

case "$(playerctl -l)" in
  spotify|google-play-music-desktop-player|clementine)
    playerctl previous
    ;;
esac

if [ -n "$(pidof pianobar)" ]; then
  echo -n 'p' > ~/.config/pianobar/ctl
  exit
fi

if [ -n "$(pidof mplayer)" ]; then
  echo 'pt_step -1' > /tmp/mplayer
  exit
fi

if [ -n "$(pidof cmus)" ]; then
  cmus-remote -r
  exit
fi

if [ -n "$(pidof sconsify)" ]; then
  sconsify -command replay
  exit
fi
