#!/bin/sh

# pgrep pianobar
# if [ $? -eq 0 ]; then
#   echo -n '(' > ~/.config/pianobar/ctl
# else
#   amixer -q sset Master 5%-
# fi

SINK=$(pactl list sinks short | grep RUNNING | awk {'print $1'})
pactl set-sink-volume $SINK -5%
